# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-25 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('reg_date', models.DateTimeField(verbose_name='date registered')),
                ('brief', models.IntegerField(default=-1)),
                ('consent', models.BooleanField(default=False)),
            ],
        ),
    ]
