# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-07 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('okcoder', '0006_runlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='timestamp')),
                ('event', models.CharField(max_length=100)),
                ('info', models.CharField(max_length=100)),
                ('partnership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='okcoder.Partnership')),
            ],
        ),
    ]
