# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-01-25 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('okcoder', '0007_eventlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletionCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='eventlog',
            name='newxy',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='oldxy',
            field=models.CharField(default='', max_length=100),
        ),
    ]
